# Site settings

# Title of your site
title: corey611 

# Your contant email
email: corey611@outlook.com 

# this means to ignore newlines until "baseurl:"
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# the subpath of your site, e.g. /blog/
baseurl: "" 

# the base hostname & protocol for your site
url: "http://corey611.com" 

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     example  # Replace this with your Twitter username
github_username:      corey611  # Replace this with your GitHub username
linkedin_username:    example  # Replace this with your LinkedIn username
google_plus_username: example  # Replace this with your Google+ username
facebook_username:    example  # Replace this with your Facebook username
dribbble_username:    example  # Replace this with your Dribbble username

# Build settings
markdown: kramdown
